// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/proto.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailCodeReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	From                 string   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailCodeReq) Reset()         { *m = SendEmailCodeReq{} }
func (m *SendEmailCodeReq) String() string { return proto.CompactTextString(m) }
func (*SendEmailCodeReq) ProtoMessage()    {}
func (*SendEmailCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{0}
}

func (m *SendEmailCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailCodeReq.Unmarshal(m, b)
}
func (m *SendEmailCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailCodeReq.Marshal(b, m, deterministic)
}
func (m *SendEmailCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailCodeReq.Merge(m, src)
}
func (m *SendEmailCodeReq) XXX_Size() int {
	return xxx_messageInfo_SendEmailCodeReq.Size(m)
}
func (m *SendEmailCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailCodeReq proto.InternalMessageInfo

func (m *SendEmailCodeReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendEmailCodeReq) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

type SendEmailCodeRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailCodeRes) Reset()         { *m = SendEmailCodeRes{} }
func (m *SendEmailCodeRes) String() string { return proto.CompactTextString(m) }
func (*SendEmailCodeRes) ProtoMessage()    {}
func (*SendEmailCodeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{1}
}

func (m *SendEmailCodeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailCodeRes.Unmarshal(m, b)
}
func (m *SendEmailCodeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailCodeRes.Marshal(b, m, deterministic)
}
func (m *SendEmailCodeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailCodeRes.Merge(m, src)
}
func (m *SendEmailCodeRes) XXX_Size() int {
	return xxx_messageInfo_SendEmailCodeRes.Size(m)
}
func (m *SendEmailCodeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailCodeRes.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailCodeRes proto.InternalMessageInfo

func (m *SendEmailCodeRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SendEmailCodeRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RegisterReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{2}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RegisterRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Uid                  int64    `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	LastLoginAt          string   `protobuf:"bytes,7,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Token                string   `protobuf:"bytes,9,opt,name=token,proto3" json:"token,omitempty"`
	Roles                []string `protobuf:"bytes,10,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRes) Reset()         { *m = RegisterRes{} }
func (m *RegisterRes) String() string { return proto.CompactTextString(m) }
func (*RegisterRes) ProtoMessage()    {}
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{3}
}

func (m *RegisterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRes.Unmarshal(m, b)
}
func (m *RegisterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRes.Marshal(b, m, deterministic)
}
func (m *RegisterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRes.Merge(m, src)
}
func (m *RegisterRes) XXX_Size() int {
	return xxx_messageInfo_RegisterRes.Size(m)
}
func (m *RegisterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRes.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRes proto.InternalMessageInfo

func (m *RegisterRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RegisterRes) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RegisterRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRes) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *RegisterRes) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRes) GetLastLoginAt() string {
	if m != nil {
		return m.LastLoginAt
	}
	return ""
}

func (m *RegisterRes) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *RegisterRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterRes) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type LoginReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{4}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PasswordBackReq struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordBackReq) Reset()         { *m = PasswordBackReq{} }
func (m *PasswordBackReq) String() string { return proto.CompactTextString(m) }
func (*PasswordBackReq) ProtoMessage()    {}
func (*PasswordBackReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{5}
}

func (m *PasswordBackReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordBackReq.Unmarshal(m, b)
}
func (m *PasswordBackReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordBackReq.Marshal(b, m, deterministic)
}
func (m *PasswordBackReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordBackReq.Merge(m, src)
}
func (m *PasswordBackReq) XXX_Size() int {
	return xxx_messageInfo_PasswordBackReq.Size(m)
}
func (m *PasswordBackReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordBackReq.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordBackReq proto.InternalMessageInfo

func (m *PasswordBackReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *PasswordBackReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PasswordBackReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PasswordBackRes struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordBackRes) Reset()         { *m = PasswordBackRes{} }
func (m *PasswordBackRes) String() string { return proto.CompactTextString(m) }
func (*PasswordBackRes) ProtoMessage()    {}
func (*PasswordBackRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{6}
}

func (m *PasswordBackRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordBackRes.Unmarshal(m, b)
}
func (m *PasswordBackRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordBackRes.Marshal(b, m, deterministic)
}
func (m *PasswordBackRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordBackRes.Merge(m, src)
}
func (m *PasswordBackRes) XXX_Size() int {
	return xxx_messageInfo_PasswordBackRes.Size(m)
}
func (m *PasswordBackRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordBackRes.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordBackRes proto.InternalMessageInfo

func (m *PasswordBackRes) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PasswordBackRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DataFullReq struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataFullReq) Reset()         { *m = DataFullReq{} }
func (m *DataFullReq) String() string { return proto.CompactTextString(m) }
func (*DataFullReq) ProtoMessage()    {}
func (*DataFullReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{7}
}

func (m *DataFullReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataFullReq.Unmarshal(m, b)
}
func (m *DataFullReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataFullReq.Marshal(b, m, deterministic)
}
func (m *DataFullReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataFullReq.Merge(m, src)
}
func (m *DataFullReq) XXX_Size() int {
	return xxx_messageInfo_DataFullReq.Size(m)
}
func (m *DataFullReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DataFullReq.DiscardUnknown(m)
}

var xxx_messageInfo_DataFullReq proto.InternalMessageInfo

func (m *DataFullReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DataFullReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataFullReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *DataFullReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Res struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Res) Reset()         { *m = Res{} }
func (m *Res) String() string { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()    {}
func (*Res) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{8}
}

func (m *Res) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Res.Unmarshal(m, b)
}
func (m *Res) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Res.Marshal(b, m, deterministic)
}
func (m *Res) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Res.Merge(m, src)
}
func (m *Res) XXX_Size() int {
	return xxx_messageInfo_Res.Size(m)
}
func (m *Res) XXX_DiscardUnknown() {
	xxx_messageInfo_Res.DiscardUnknown(m)
}

var xxx_messageInfo_Res proto.InternalMessageInfo

func (m *Res) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Res) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SendEmailCodeReq)(nil), "send_email_code_req")
	proto.RegisterType((*SendEmailCodeRes)(nil), "send_email_code_res")
	proto.RegisterType((*RegisterReq)(nil), "register_req")
	proto.RegisterType((*RegisterRes)(nil), "register_res")
	proto.RegisterType((*LoginReq)(nil), "login_req")
	proto.RegisterType((*PasswordBackReq)(nil), "password_back_req")
	proto.RegisterType((*PasswordBackRes)(nil), "password_back_res")
	proto.RegisterType((*DataFullReq)(nil), "data_full_req")
	proto.RegisterType((*Res)(nil), "res")
}

func init() { proto.RegisterFile("api/proto/proto.proto", fileDescriptor_ef32c37ea206d67b) }

var fileDescriptor_ef32c37ea206d67b = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcf, 0xcf, 0xd2, 0x40,
	0x10, 0xb5, 0x5f, 0x5b, 0x3e, 0x3a, 0x5a, 0x7f, 0xac, 0x68, 0x36, 0x4d, 0x4c, 0xc8, 0xea, 0xc1,
	0x68, 0x52, 0x13, 0xbd, 0x48, 0x8c, 0x21, 0x78, 0xf6, 0xc4, 0x4d, 0x2f, 0xcd, 0x42, 0x17, 0xd2,
	0xd0, 0x76, 0x71, 0x77, 0xd1, 0x3f, 0xdd, 0x78, 0x33, 0x33, 0x2d, 0x48, 0x69, 0x35, 0x78, 0x29,
	0x6f, 0x1e, 0x33, 0x6f, 0x86, 0x79, 0x43, 0xe1, 0x89, 0xdc, 0x17, 0x6f, 0xf6, 0x46, 0x3b, 0xdd,
	0x3c, 0x53, 0x7a, 0x8a, 0x39, 0x3c, 0xb6, 0xaa, 0xce, 0x33, 0x55, 0xc9, 0xa2, 0xcc, 0xd6, 0x3a,
	0x57, 0x99, 0x51, 0xdf, 0xd8, 0x04, 0x42, 0x62, 0xb8, 0x37, 0xf5, 0x5e, 0x46, 0xcb, 0x26, 0x60,
	0x0c, 0x82, 0x8d, 0xd1, 0x15, 0xbf, 0x21, 0x92, 0xb0, 0xf8, 0x30, 0x24, 0x60, 0x31, 0x15, 0x31,
	0xd5, 0xfb, 0x4b, 0xc2, 0xec, 0x21, 0xf8, 0x95, 0xdd, 0xb6, 0xd5, 0x08, 0xc5, 0x7b, 0xb8, 0x67,
	0xd4, 0xb6, 0xb0, 0x4e, 0x99, 0x7f, 0xb7, 0x25, 0xad, 0xb6, 0x2d, 0x62, 0xf1, 0xd3, 0xeb, 0x94,
	0x5e, 0xd9, 0x10, 0x99, 0x43, 0x91, 0x73, 0x9f, 0x92, 0x10, 0x62, 0x5d, 0x2d, 0x2b, 0xc5, 0x83,
	0x46, 0x1c, 0x31, 0x7b, 0x0a, 0x23, 0xf9, 0x5d, 0x3a, 0x69, 0x78, 0x48, 0x6c, 0x1b, 0xfd, 0x19,
	0x6f, 0x74, 0x3e, 0x9e, 0x80, 0xb8, 0x94, 0xd6, 0x65, 0xa5, 0xde, 0x16, 0x75, 0x26, 0x1d, 0xbf,
	0xa5, 0x6f, 0xef, 0x22, 0xf9, 0x19, 0xb9, 0x85, 0x63, 0xcf, 0x00, 0xd6, 0x46, 0x49, 0xa7, 0x72,
	0x4c, 0x18, 0x53, 0x42, 0xd4, 0x32, 0x0b, 0x87, 0xc2, 0x4e, 0xef, 0x54, 0xcd, 0xa3, 0x46, 0x98,
	0x02, 0x64, 0x8d, 0x2e, 0x95, 0xe5, 0x30, 0xf5, 0x91, 0xa5, 0x40, 0x7c, 0x84, 0xa8, 0xe9, 0xf4,
	0xf7, 0x85, 0x25, 0x30, 0xde, 0x4b, 0x6b, 0x7f, 0x68, 0x93, 0xb7, 0x3f, 0xfe, 0x14, 0x8b, 0x2f,
	0xf0, 0xe8, 0x88, 0xb3, 0x95, 0x5c, 0xef, 0xfe, 0x6f, 0xef, 0x1d, 0x69, 0xff, 0x42, 0x7a, 0xd6,
	0x97, 0xbe, 0xf6, 0x10, 0x0a, 0x88, 0x73, 0xe9, 0x64, 0xb6, 0x39, 0x94, 0x25, 0x4d, 0xd4, 0x1a,
	0xe5, 0xf5, 0x8d, 0xba, 0x19, 0x34, 0xca, 0xef, 0x18, 0x75, 0x3e, 0x65, 0x70, 0x31, 0xe5, 0x6b,
	0xf0, 0xaf, 0x9e, 0xeb, 0xed, 0x2f, 0x0f, 0x82, 0x83, 0x55, 0x86, 0xcd, 0xe1, 0xc1, 0xc5, 0x99,
	0xb3, 0x49, 0x3a, 0xf0, 0xcf, 0x49, 0x86, 0x58, 0x2b, 0xee, 0xb0, 0x57, 0x30, 0x3e, 0xde, 0x2b,
	0x8b, 0xd3, 0xf3, 0xab, 0x4f, 0x3a, 0x21, 0xe6, 0xbe, 0x80, 0x90, 0x2c, 0x66, 0x90, 0x9e, 0xac,
	0xee, 0x67, 0xcd, 0x20, 0xee, 0xac, 0x9b, 0xb1, 0xb4, 0xe7, 0x6c, 0xd2, 0xe7, 0xb0, 0xf4, 0x39,
	0x44, 0xa7, 0x75, 0xb3, 0xfb, 0x69, 0x67, 0xf5, 0x49, 0x90, 0x52, 0xd2, 0xa7, 0xdb, 0xaf, 0x21,
	0xbd, 0x23, 0x56, 0x23, 0xfa, 0x78, 0xf7, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xa2, 0xf3, 0x58,
	0x43, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	SendEmailCode(ctx context.Context, in *SendEmailCodeReq, opts ...grpc.CallOption) (*SendEmailCodeRes, error)
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error)
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*RegisterRes, error)
	PasswordBack(ctx context.Context, in *PasswordBackReq, opts ...grpc.CallOption) (*PasswordBackRes, error)
	DataFull(ctx context.Context, in *DataFullReq, opts ...grpc.CallOption) (*Res, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) SendEmailCode(ctx context.Context, in *SendEmailCodeReq, opts ...grpc.CallOption) (*SendEmailCodeRes, error) {
	out := new(SendEmailCodeRes)
	err := c.cc.Invoke(ctx, "/user/send_email_code", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	out := new(RegisterRes)
	err := c.cc.Invoke(ctx, "/user/register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	out := new(RegisterRes)
	err := c.cc.Invoke(ctx, "/user/login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) PasswordBack(ctx context.Context, in *PasswordBackReq, opts ...grpc.CallOption) (*PasswordBackRes, error) {
	out := new(PasswordBackRes)
	err := c.cc.Invoke(ctx, "/user/password_back", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DataFull(ctx context.Context, in *DataFullReq, opts ...grpc.CallOption) (*Res, error) {
	out := new(Res)
	err := c.cc.Invoke(ctx, "/user/data_full", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	SendEmailCode(context.Context, *SendEmailCodeReq) (*SendEmailCodeRes, error)
	Register(context.Context, *RegisterReq) (*RegisterRes, error)
	Login(context.Context, *LoginReq) (*RegisterRes, error)
	PasswordBack(context.Context, *PasswordBackReq) (*PasswordBackRes, error)
	DataFull(context.Context, *DataFullReq) (*Res, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) SendEmailCode(ctx context.Context, req *SendEmailCodeReq) (*SendEmailCodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmailCode not implemented")
}
func (*UnimplementedUserServer) Register(ctx context.Context, req *RegisterReq) (*RegisterRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServer) Login(ctx context.Context, req *LoginReq) (*RegisterRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServer) PasswordBack(ctx context.Context, req *PasswordBackReq) (*PasswordBackRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasswordBack not implemented")
}
func (*UnimplementedUserServer) DataFull(ctx context.Context, req *DataFullReq) (*Res, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DataFull not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_SendEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SendEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user/SendEmailCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SendEmailCode(ctx, req.(*SendEmailCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_PasswordBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordBackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).PasswordBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user/PasswordBack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).PasswordBack(ctx, req.(*PasswordBackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DataFull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataFullReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DataFull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user/DataFull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DataFull(ctx, req.(*DataFullReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "send_email_code",
			Handler:    _User_SendEmailCode_Handler,
		},
		{
			MethodName: "register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "password_back",
			Handler:    _User_PasswordBack_Handler,
		},
		{
			MethodName: "data_full",
			Handler:    _User_DataFull_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/proto.proto",
}
